version: '3.7'

x-default-opts: &default-opts
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  change_this_service_name:
    <<: *default-opts
    image: nginx:alpine
    container_name: change_this_service_name
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    networks:
      - proxy
    labels:
      # Traefik label
      - "traefik.enable=true"

      # Asociates router with your specific domain or subdomain and websecure (https)
      - "traefik.http.routers.change_this_service_name.rule=Host(`change_this_service_url`)"
      - "traefik.http.routers.change_this_service_name.entrypoints=websecure"

      # Enables tls
      # If theres is no cert for the domain or subdomain traefik creates it and save it to json in shared volume
      # If any cert is to be expired, traefik creates a new one too
      - "traefik.http.routers.change_this_service_name.tls=true"

      # Asociation with resolver (see static.yml file)
      - "traefik.http.routers.change_this_service_name.tls.certresolver=resolver"

      # add security middleware
      - "traefik.http.routers.change_this_service_name.middlewares=security-headers"

      # Set default options (see dynamic.yaml for this)
      - "traefik.http.routers.change_this_service_name.tls.options=default"

      - "traefik.http.routers.change_this_service_name.middlewares=change_this_service_name-auth"
      # Use [ echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g ] to generate new password
      - "traefik.http.middlewares.change_this_service_name-auth.basicauth.users=user:$$apr1$$LhjsBaqL$$11XInqy4VSh.HDaNDQfD5/"

networks:
  proxy:
    external: true
